name: ${project.name}
main: WTFlagsPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: false
depend: [WorldGuard, WorldEdit]
softdepend: [ProtocolLib]
authors: [X_Niter]
api-version: 1.16.5-R0.1